# DBT project for Fudgemart / Fudgeflix order fulfillment

name: 'fudgemart'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# Paths where dbt will look for different types of files
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Where compiled SQL will be stored
target-path: "target"  
clean-targets:         
  - "target"
  - "dbt_packages"

# Configuring models
# By default, all models in this project will be materialized as tables in the analytics database
models:
    +materialized: table
    +database: analytics
    +schema: fudgemart   
